const REWARDS_PROFILE_IMAGE_UPDATE = 'REWARDS_PROFILE_IMAGE_UPDATE';
const REWARDS_PROFILE_IMAGE_UPDATE_FLAG = 'REWARDS_PROFILE_IMAGE_UPDATE_FLAG';
const USER_CONFIG_UPDATE = 'USER_CONFIG_UPDATE';
const DELETE_REWARDS_ACCOUNT = 'DELETE_REWARDS_ACCOUNT';

export {
  REWARDS_PROFILE_IMAGE_UPDATE,
  REWARDS_PROFILE_IMAGE_UPDATE_FLAG,
  USER_CONFIG_UPDATE,
  DELETE_REWARDS_ACCOUNT
};
