const GET_PAYSLIP = "GET_PAYSLIP";
const GET_PAYSLIP_DETAILS = "GET_PAYSLIP_DETAILS";
const GET_PAYSLIP_DOCUMENT = "GET_PAYSLIP_DOCUMENT";
const GET_ABSENSE_TYPE = "GET_ABSENSE_TYPE";
const GET_ABSENSE_BALANCE = "GET_ABSENSE_BALANCE";
const HR_APPLY_LEAVE = "HR_APPLY_LEAVE";
const GET_ABSENSE_DATA = "GET_ABSENSE_DATA";
const CANCEL_ABSENSE_DATA = "CANCEL_ABSENSE_DATA";
const GET_ABSENSE_REASONS = "GET_ABSENSE_REASONS";
const GET_ATTENDANCE = "GET_ATTENDANCE";
const CREATE_PUBLIC_HOLIDAY = "CREATE_PUBLIC_HOLIDAY";
const GET_PUBLIC_HOLIDAY_STATUS = "GET_PUBLIC_HOLIDAY_STATUS";

export {
  GET_PAYSLIP,
  GET_PAYSLIP_DOCUMENT,
  GET_ABSENSE_TYPE,
  GET_ABSENSE_BALANCE,
  HR_APPLY_LEAVE,
  GET_ABSENSE_DATA,
  CANCEL_ABSENSE_DATA,
  GET_ABSENSE_REASONS,
  GET_PAYSLIP_DETAILS,
  GET_ATTENDANCE,
  CREATE_PUBLIC_HOLIDAY,
  GET_PUBLIC_HOLIDAY_STATUS,
};
