let ks = {
  dob: [],
  joiningDate: [],
  workAnniversaryQuery: [
    {
      addresses: [Array],
      auth_type: "azure_ad",
      blood_type: null,
      business_unit_name: "ACC Business Unit",
      citizenships: null,
      country_of_birth: null,
      created_date: "2024-03-18T08:58:04.201Z",
      date_of_birth: "1997-05-25",
      department_name: "Operations",
      display_name: "Abdullah Alzahrani",
      emails: [Array],
      employee_id: 3664,
      first_name: "Abdullah",
      gender: "M",
      id: 412,
      is_active: true,
      is_app_installed: false,
      is_deleted: false,
      joining_date: "2023-06-04T00:00:00.000Z",
      last_failed_logged_date: null,
      last_name: "Alzahrani",
      last_profile_sync_date: "2024-06-06T09:46:32.573Z",
      last_successful_logged_date: null,
      last_sync_date: "2024-05-31T08:30:51.883Z",
      line_manager: [Object],
      local_display_name: "Mr.عبدالله الزهراني",
      local_first_name: "عبدالله",
      local_last_name: "الزهراني",
      local_middle_names: null,
      local_title: "MR.",
      managers: [Array],
      marital_status: "S",
      middle_names: null,
      name_language: "US",
      national_identifiers: [Array],
      onboarded: false,
      organization_id: 1,
      passports: [Array],
      password: null,
      phones: [Array],
      photo: null,
      profile_image_url: null,
      refresh_token: null,
      religion: "MUSLIM",
      time_zone: "Asia/Riyadh",
      title: "MR.",
      updated_date: "2024-05-31T08:30:51.884Z",
      user_id: 414,
      user_type: "employee",
      username: "abdullah.hassan@cenomi.com",
      version: 5,
      work_relationships: [Array],
    },
  ],
};

let greetings = [
  {
    createdAt: "2024-05-27T07:29:38.075Z",
    greetingCardImage: {
      contentType: "image/png",
      description: "Eid Al-Adha Cenomi One greeting card",
      fileName: "EID GREETING NAME.png",
      height: 824,
      id: "TqJgyZZO6J3vpLYxcjoU6",
      isActive: true,
      locale: "en-US",
      size: 249943,
      tags: [Array],
      title: "Eid Al-Adha Cenomi One greeting card",
      url: "//images.ctfassets.net/01phmrb9fsp7/TqJgyZZO6J3vpLYxcjoU6/489b50083da6cfc48eb53926ac12e95b/EID_GREETING_NAME.png",
      width: 824,
    },
    id: "5qbGOkljyNaqMM17mnE3Oc",
    internalName: "Eid Al-Adha Cenomi One greeting card",
    isActive: true,
    locale: "en-US",
    status: "",
    tags: [],
    title: "Eid Al-Adha Cenomi One greeting card",
    updatedAt: "2024-05-27T07:29:38.075Z",
    validFor: [[Object]],
  },
  {
    createdAt: "2024-04-01T08:57:34.640Z",
    greetingCardImage: {
      contentType: "image/jpeg",
      description: "Eid Greeting image",
      fileName: "EID GREETING NAME.jpg",
      height: 823,
      id: "7ex8vOHn5lFLLB9FhmoZGV",
      isActive: true,
      locale: "en-US",
      size: 215696,
      tags: [Array],
      title: "Eid Greeting image",
      url: "//images.ctfassets.net/01phmrb9fsp7/7ex8vOHn5lFLLB9FhmoZGV/d2c83e178eacde05649af2d06c431924/EID_GREETING_NAME.jpg",
      width: 823,
    },
    id: "5zgaIuyyZh39yChCKoMxiW",
    internalName: "Eid Greeting",
    isActive: true,
    locale: "en-US",
    status: "",
    tags: [],
    title: "Eid Greeting",
    updatedAt: "2024-04-01T08:57:34.640Z",
    validFor: [[Object]],
  },
];

let send = {
  dob: [],
  joiningDate: [],
  workAnniversaryQuery: [
    {
      addresses: [Array],
      auth_type: "azure_ad",
      blood_type: null,
      business_unit_name: "ACC Business Unit",
      citizenships: null,
      country_of_birth: null,
      created_date: "2024-03-18T08:58:04.201Z",
      date_of_birth: "1997-05-25",
      department_name: "Operations",
      display_name: "Abdullah Alzahrani",
      emails: [Array],
      employee_id: 3664,
      first_name: "Abdullah",
      gender: "M",
      id: 412,
      is_active: true,
      is_app_installed: false,
      is_deleted: false,
      joining_date: "2023-06-04T00:00:00.000Z",
      last_failed_logged_date: null,
      last_name: "Alzahrani",
      last_profile_sync_date: "2024-06-06T09:46:32.573Z",
      last_successful_logged_date: null,
      last_sync_date: "2024-05-31T08:30:51.883Z",
      line_manager: [Object],
      local_display_name: "Mr.عبدالله الزهراني",
      local_first_name: "عبدالله",
      local_last_name: "الزهراني",
      local_middle_names: null,
      local_title: "MR.",
      managers: [Array],
      marital_status: "S",
      middle_names: null,
      name_language: "US",
      national_identifiers: [Array],
      onboarded: false,
      organization_id: 1,
      passports: [Array],
      password: null,
      phones: [Array],
      photo: null,
      profile_image_url: null,
      refresh_token: null,
      religion: "MUSLIM",
      time_zone: "Asia/Riyadh",
      title: "MR.",
      updated_date: "2024-05-31T08:30:51.884Z",
      user_id: 414,
      user_type: "employee",
      username: "abdullah.hassan@cenomi.com",
      version: 5,
      work_relationships: [Array],
    },
  ],
};

// let api = {"clarifyTimeoutError": false, "forcedJSONParsing": true, "silentJSONParsing": true}, "url": "cms/greetings", "validateStatus": [Function validateStatus], "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN"},
let res = [
  {
    createdAt: "2024-05-27T07:29:38.075Z",
    greetingCardImage: [Object],
    id: "5qbGOkljyNaqMM17mnE3Oc",
    internalName: "Eid Al-Adha Cenomi One greeting card",
    isActive: true,
    locale: "en-US",
    status: "",
    tags: [Array],
    title: "Eid Al-Adha Cenomi One greeting card",
    updatedAt: "2024-05-27T07:29:38.075Z",
    validFor: [Array],
  },
  {
    createdAt: "2024-04-01T08:57:34.640Z",
    greetingCardImage: [Object],
    id: "5zgaIuyyZh39yChCKoMxiW",
    internalName: "Eid Greeting",
    isActive: true,
    locale: "en-US",
    status: "",
    tags: [Array],
    title: "Eid Greeting",
    updatedAt: "2024-04-01T08:57:34.640Z",
    validFor: [Array],
  },
];

let kk = {
  config: {
    adapter: ["xhr", "http", "fetch"],
    baseURL: "https://one.cenomi.com/api/v2/",
    data: undefined,
    env: { Blob: [], FormData: [] },
    headers: [Object],
    maxBodyLength: -1,
    maxContentLength: -1,
    metadata: {
      httpMetric: [HttpMetric],
      requestEndTime: 1717671510217,
      requestStartTime: 1717671507065,
    },
    method: "get",
    timeout: 0,
    transformRequest: [[]],
    transformResponse: [[]],
    transitional: {
      clarifyTimeoutError: false,
      forcedJSONParsing: true,
      silentJSONParsing: true,
    },
    url: "process/hr-request/wishes",
    validateStatus: [],
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
  },
  data: { dob: [], joiningDate: [], workAnniversaryQuery: [[Object]] },
};
