const PROFILE_IMAGE_UPDATE = 'PROFILE_IMAGE_UPDATE';
const PROFILE_IMAGE_UPDATE_FLAG = 'PROFILE_IMAGE_UPDATE_FLAG';
const USER_CONFIG_UPDATE = 'USER_CONFIG_UPDATE';

export { PROFILE_IMAGE_UPDATE, USER_CONFIG_UPDATE, PROFILE_IMAGE_UPDATE_FLAG };
