const GET_APPROVAL_PENDINGTASKS = 'get_Approval_PendingTasks';
const GET_APPROVAL_TASKS_DETAILS = 'get_Approval_Tasks_Details';

const GET_WORKFLOW_PENDINGTASKS = 'get_Workflow_PendingTasks';
const GET_WORKFLOW_TASKS_DETAILS = 'get_Workflow_Tasks_Details';
const GET_WORKFLOW_USERS_LIST = 'get_workflow_users';

const GET_APPROVAL_TASKS_COUNT = 'get_Approval_Tasks_count';

const PUT_APPROVAL_ACTION = 'put_approval_action';
const GET_USER_SEARCH_LIST = 'get_user_search';

const APPROVAL_ACTION_DONE = 'approval_action_done';

const GET_LEASING_PENDINGTASKS = 'getLeasingPendingTasks';
const GET_LEASING_TASKS_DETAILS = 'get_Leasing_Tasks_Details';
const PUT_LEASING_TAKE_ACTION = 'put_leasing_take_action';

const GET_LEASING_TASKS_ATTACHMENTS = 'get_Leasing_Tasks_Attachments';

const GET_PROCUREMENT_PENDINGTASK = 'getProcurementPendingTask';
const GET_PROCUREMENT_TASK_DETAILS = 'getProcurementTaskDetails';
const PUT_PROCUREMENT_ACTION = 'put_procurement_action';

export {
  GET_APPROVAL_PENDINGTASKS,
  GET_APPROVAL_TASKS_DETAILS,
  GET_USER_SEARCH_LIST,
  GET_APPROVAL_TASKS_COUNT,
  PUT_APPROVAL_ACTION,
  APPROVAL_ACTION_DONE,
  GET_LEASING_PENDINGTASKS,
  GET_LEASING_TASKS_DETAILS,
  PUT_LEASING_TAKE_ACTION,
  GET_LEASING_TASKS_ATTACHMENTS,
  GET_PROCUREMENT_PENDINGTASK,
  GET_PROCUREMENT_TASK_DETAILS,
  PUT_PROCUREMENT_ACTION,
  GET_WORKFLOW_PENDINGTASKS,
  GET_WORKFLOW_TASKS_DETAILS,
  GET_WORKFLOW_USERS_LIST,
};
