const FILE_UPLOAD = 'FILE_UPLOAD';
const FILE_PREVIEW = 'FILE_PREVIEW';
const SYNC_PROFILE = 'SYNC_PROFILE';
const UPDATE_SYNC_PROFILE_FLAG = 'UPDATE_SYNC_PROFILE_FLAG';
const MARK_ONBOARDED = 'MARK_ONBOARDED';
const UPDATE_MARK_ONBOARDED_FLAG = 'UPDATE_SYNC_PROFILE_FLAG';
const GET_STATIC_DATA = 'GET_STATIC_DATA';
const GET_PUBLIC_STATIC_DATA = 'GET_PUBLIC_STATIC_DATA';

const SET_COLOR_THEME = 'SET_COLOR_THEME';
const SEND_WISHES_INFO = 'SEND_WISHES_INFO';
const GREETINGS_DATA = 'GREETINGS_DATA';

const SET_IS_CHAT_WINDOW_VISIBLE = 'SET_IS_CHAT_WINDOW_VISIBLE';
const ORGANIZATION_CONFIG = 'ORGANIZATION_CONFIG';
const NEWS_LIST = 'NEWS_LIST';
const TENANT_FILE_UPLOAD = 'TENANT_FILE_UPLOAD';

export {
  FILE_UPLOAD,
  FILE_PREVIEW,
  SYNC_PROFILE,
  UPDATE_SYNC_PROFILE_FLAG,
  MARK_ONBOARDED,
  UPDATE_MARK_ONBOARDED_FLAG,
  GET_STATIC_DATA,
  GET_PUBLIC_STATIC_DATA,
  SET_COLOR_THEME,
  SEND_WISHES_INFO,
  GREETINGS_DATA,
  SET_IS_CHAT_WINDOW_VISIBLE,
  ORGANIZATION_CONFIG,
  NEWS_LIST,
  TENANT_FILE_UPLOAD
};
